apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-provisioner
  labels:
    app: nfs-server-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-provisioner
  template:
    metadata:
      labels:
        app: nfs-server-provisioner
    spec:
      containers:
      - name: nfs-server-provisioner
        image: gcr.io/k8s-staging-sig-storage/nfs-provisioner:latest
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: nfs-storage
          mountPath: /export
      volumes:
      - name: nfs-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
  - port: 2049
    name: nfs
  - port: 20048
    name: mountd
  - port: 111
    name: rpcbind
  selector:
    app: nfs-server-provisioner

